Db:
  host: localhost
  user: root
  password: 
  database: job_share_prod
  port: 3306

faiss:
  path: "./faiss_data"
  index_file: "jobs_index.faiss"
  payload_file: "payloads.pkl"

LLM_Model:
  embedding_model: openai/text-embedding-3-small
  vector_size: 1536
  parse_model: openai/gpt-4o-mini